[workspace]
resolver = "2"
members = [
    "crates/smm-core",
    "crates/smm-cli",
    "apps/smm-desktop/src-tauri",
]

[workspace.package]
version = "0.1.7"
edition = "2021"
authors = ["Sekiro Mod Manager Contributors"]
license = "MIT"
repository = "https://github.com/RolinShmily/sekiro-mod-manager"
