# Seed a demo library so every screen has something real to show.
#
# Half of this UI is about conflicts and precedence, and those are exactly the states you cannot
# review against an empty staging area. The library below is laid out deliberately:
#
#   * two parameter mods sharing param\gameparam\gameparam.parambnd.dcx  -> a CRITICAL conflict
#   * two weapon mods sharing parts\wp_a_0300.partsbnd.dcx               -> an exclusive-slot clash
#   * a mod that loses every file it has                                 -> "fully taken over" state
#   * several clean mods                                                 -> bands in the fingerprint
#
# Idempotent: re-running replaces the same mods. It also points the app at this library through
# `smm config`, which is the same setting the Settings page writes.

$ErrorActionPreference = 'Stop'

$root    = Join-Path $env:TEMP 'smm-demo'
$staging = Join-Path $root 'staging'
$game    = Join-Path $root 'game'
$src     = Join-Path $root 'pkgs'
$smm     = Join-Path $PSScriptRoot '..\..\build\gui\src\cli\smm.exe'
$smm     = [System.IO.Path]::GetFullPath($smm)

if (-not (Test-Path $smm)) {
    Write-Error "smm.exe not found at $smm`nBuild it first:  cmake --preset msvc-x64-debug ; cmake --build --preset build-debug --target smm"
}

# id, display name, priority (lower wins), and the asset paths the mod provides.
$mods = @(
    @{ Id = 'gameparam-rebalance-v3';  Name = 'GameParam Rebalance';   Priority = 60;
       Files = @('param\gameparam\gameparam.parambnd.dcx') }
    @{ Id = 'boss-rebalance-v2';       Name = 'Boss Rebalance';        Priority = 40;
       Files = @('param\gameparam\gameparam.parambnd.dcx') }
    @{ Id = 'kusabimaru-reaper-v1-2';  Name = 'Kusabimaru Reaper';     Priority = 30;
       Files = @('chr\c5110.chrbnd.dcx', 'parts\wp_a_0300.partsbnd.dcx') }
    @{ Id = 'mortal-blade-glow-v2';    Name = 'Mortal Blade Glow';     Priority = 70;
       Files = @('parts\wp_a_0310.partsbnd.dcx') }
    @{ Id = 'dream-of-the-damned-v1';  Name = 'Dream Of The Damned';   Priority = 20;
       Files = @('parts\wp_a_0300.partsbnd.dcx', 'parts\wp_a_0310.partsbnd.dcx') }
    @{ Id = 'chinese-ui-v1';           Name = 'Chinese UI';            Priority = 80;
       Files = @('menu\hi\01_common.tpf.dcx', 'menu\font\font_zh.gfx') }
    @{ Id = 'sekiro-ultrawide-fix-v1'; Name = 'Sekiro Ultrawide Fix';  Priority = 90;
       Files = @('menu\hi\04_hud.tpf.dcx') }
)

Write-Host "Seeding a demo library in $root"
foreach ($dir in @($staging, (Join-Path $game 'mods'), $src)) {
    if (Test-Path $dir) { Remove-Item -Recurse -Force $dir }
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
}

Write-Host "`nCreating source packages..."
foreach ($mod in $mods) {
    $modDir = Join-Path $src $mod.Name
    foreach ($asset in $mod.Files) {
        $target = Join-Path $modDir $asset
        New-Item -ItemType Directory -Force -Path (Split-Path -Parent $target) | Out-Null
        Set-Content -Path $target -Value "$($mod.Name) asset: $asset" -Encoding utf8
    }
    Set-Content -Path (Join-Path $modDir 'README.md') `
        -Value "$($mod.Name) - demo asset pack generated by tools\local\seed_demo.ps1" -Encoding utf8
    Write-Host "  $($mod.Name): $($mod.Files.Count) asset(s)"
}

Write-Host "`nImporting..."
$failed = 0
foreach ($mod in $mods) {
    & $smm --quiet --staging $staging import (Join-Path $src $mod.Name) `
        --id $mod.Id --name $mod.Name --priority $mod.Priority --overwrite
    if ($LASTEXITCODE -ne 0) { Write-Warning "  import failed: $($mod.Name)"; $failed++ }
}

Write-Host "`nSetting priorities (lower number wins a shared file)..."
foreach ($mod in $mods) {
    & $smm --quiet --staging $staging priority $mod.Id $mod.Priority
    if ($LASTEXITCODE -ne 0) { Write-Warning "  priority failed: $($mod.Id)"; $failed++ }
}

Write-Host "`nPointing the app at the demo library..."
& $smm config --staging $staging --game-dir $game
if ($LASTEXITCODE -ne 0) { Write-Error "could not save the configuration" }

Write-Host ''
& $smm --staging $staging list
Write-Host ''
& $smm --staging $staging conflicts

Write-Host ''
if ($failed -gt 0) {
    Write-Warning "$failed step(s) failed."
    exit 1
}
Write-Host 'Done. Launch with:  tools\local\run_gui.bat'
